### ISSUE TITLE
timestamp bug at pymata-express.py [async def analog_message(self, data)]

### ISSUE THREAD

**Issue by MJPees** [MrYsLab/pymata-express#10]
Hi,
I 've found a litte bug...

The timestamp for analog_read() is wrong.

line: self.digital_pins[pin].event_time = time_stamp
should be: self.analog_pins[pin].event_time = time_stamp

at

async def _analog_message(self, data):
        """
        This is a private message handler method.
        It is a message handler for analog messages.
        :param data: message data
        """
        pin = data[0]
        value = (data[PrivateConstants.MSB] << 7) + data[PrivateConstants.LSB]

        # only report when there is a change in value
        differential = abs(value - self.analog_pins[pin].current_value)
        if differential >= self.analog_pins[pin].differential:
            self.analog_pins[pin].current_value = value
            time_stamp = time.time()
            self.digital_pins[pin].event_time = time_stamp

            # append pin number, pin value, and pin type to return value and return as a list
            message = [pin, value, PrivateConstants.ANALOG, time_stamp]

**Comment by MrYsLab** [comment]
Hi Marc. Thank you for reporting that bug. Version 1.8 contains the fix and is available on pypi.
