### ISSUE TITLE
Compile problem Arduino Mega Board

### ISSUE THREAD

**Issue by davizucon** [MrYsLab/pymata-express#25]
Hi, 

 Maybe I doing something wrong, but when trying to compile I got:
Board Mega2560
IDE 1.8.12 
firmataexpress version 1.1.1

`/var/folders/q0/0j0022zd5l94lxs6r282q1t80000gn/T//ccP9Lor6.ltrans0.ltrans.o: In function `sysexCallback(unsigned char, unsigned char, unsigned char*)':
<artificial>:(.text+0x2b4e): undefined reference to `operator new(unsigned int)'
<artificial>:(.text+0x2bec): undefined reference to `operator new(unsigned int)'
<artificial>:(.text+0x2c64): undefined reference to `operator new(unsigned int)'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Mega or Mega 2560.
`

**Comment by MrYsLab** [comment]
I just tried compiling on both Linux and Windows and am not seeing any errors. 
I am assuming you are using a Mac based on the directory structure. 

I don't believe that this is a bug in FirmataExpress, but a problem between macOS and the Arduino IDE.

There are many reports of incompatibilities between the Arduino IDE and the Mac. 

Here is a [sample of one of the items on the Arduino forum](https://forum.arduino.cc/index.php?topic=624061.0).

Here is the search string I used in Google to locate this information:
```
arduino 1.8.12 IDE /var/folders/
```
