### ISSUE TITLE
General Question. How can I retrieve board's pin settings?

### ISSUE THREAD

**Issue by algdev-gr** [MrYsLab/pymata-express#29]
Hello again,

Have a question. Say I set some pins as digital outputs and some others as digital inputs.
Is there a way to retirieve what pin is set how?

Tried to search the API documentation but the only solution I can think is to loop get_pin_state with all ports.
Let me know is something else is available or can be easily implemented?

Thank you.

**Comment by MrYsLab** [comment]
You can get the pin state of any pin as described[ here.](https://mryslab.github.io/pymata-express/report_requests/#get_pin_state)
The get_pin_state method will return a list containig the pin number, the pin type and current value.
