### ISSUE TITLE
[DOC typo]

### ISSUE THREAD

**Issue by wlwatkins** [MrYsLab/pymata-express#4]
Second typo on [https://mryslab.github.io/pymata-express/examples/](https://mryslab.github.io/pymata-express/examples/)

you wrote `retrieve_capbaility_report`

edit: I would also include an example for the polling function as it is not clear how to implement. for instance in the sonar example. How to poll the sonar, instead of have it stream

**Comment by MrYsLab** [comment]
Thanks. I fixed the typo and provided a [link](https://github.com/MrYsLab/pymata-express/blob/9d3d7f5976e70d55d4dd9b8cf4577f4d42751bcb/examples/digital_input.py#L55) to a polling read in the polling section of the documentation.
