### ISSUE TITLE
how use the function set_pin_mode_stepper's  pins list

### ISSUE THREAD

**Issue by HotView** [MrYsLab/pymata-express#9]
I don't know how to connect to the motor, and what is the relationship between the pin parameter in the set_pin_mode_stepper function and the motor connection?
thanks！

**Comment by MrYsLab** [comment]
Stepper motors require a driver board. This is [an example ](https://smile.amazon.com/KOOKYE-28BYJ-48-Stepper-ULN2003-Arduino/dp/B019TOJRC4/ref=sr_1_4?keywords=Stepper+Motor+28Byj-48&qid=1575978864&s=electronics&sr=1-4)of an inexpensive motor and drive electronics.

[This article](https://www.makerguides.com/28byj-48-stepper-motor-arduino-tutorial/) explains how to connect it to an Arduino.

**Comment by HotView** [comment]
First of all, thank you for your detailed answers. I think I can learn more from you in the way of answering questions.

I know that to control the stepper motor, we need a pin to control the number of steps, a pin to control the direction, an enabled pin and GND. I don't know in this pins list, such as [8,9,10,11], which represents the direction, which represents the steps, which represents the enable, etc

**Comment by HotView** [comment]
> Stepper motors require a driver board. This is [an example ](https://smile.amazon.com/KOOKYE-28BYJ-48-Stepper-ULN2003-Arduino/dp/B019TOJRC4/ref=sr_1_4?keywords=Stepper+Motor+28Byj-48&qid=1575978864&s=electronics&sr=1-4)of an inexpensive motor and drive electronics.
> 
> [This article](https://www.makerguides.com/28byj-48-stepper-motor-arduino-tutorial/) explains how to connect it to an Arduino.

@MrYsLab 
First of all, thank you for your detailed answers. I think I can learn more from you in the way of answering questions.

I know that to control the stepper motor, we need a pin to control the number of steps, a pin to control the direction, an enabled pin and GND. I don't know in this pins list, such as [8,9,10,11], which represents the direction, which represents the steps, which represents the enable, etc

**Comment by MrYsLab** [comment]
The number of steps and direction is controlled by the software. Each of the 4 pins controls one of the motor coils and not direction. The [pymata-express API method for stepper_write](https://htmlpreview.github.io/?https://github.com/MrYsLab/pymata-express/blob/master/documentation/api/pymata_express.html#pymata_express.pymata_express.PymataExpress.stepper_write)  explains how to set the number of steps and the motor direction.

**Comment by MrYsLab** [comment]
Here is [an example](https://github.com/MrYsLab/pymata-express/blob/master/examples/stepper.py) of how to use the stepper motor functions.

There are examples of pymata-express features [here](https://mryslab.github.io/pymata-express/examples/).

**Comment by HotView** [comment]
@MrYsLab 

I read the blog about your recommendation just now. The connection method is Arduino + Stepper Motor Driver + Stepper Motor, as shown in the picture.
![image](https://user-images.githubusercontent.com/16145478/70535249-aaeea680-1b97-11ea-98ea-22db6467cf7a.png)
![image](https://user-images.githubusercontent.com/16145478/70535294-c659b180-1b97-11ea-9a50-f1e7e1b49fb7.png)
 
I don’t quite understand what you mean by “ Each of the 4 pins controls one of the motor coils and not direction”. 
You mean the arduino is directly connected to the stepper motor?

**Comment by MrYsLab** [comment]
The stepper motor driver in firmata-express is based on the standard [Arduino stepper library.](https://www.arduino.cc/en/reference/stepper)

The article that I linked to in an earlier posting describes how to wire the ULN2003 motor driver board to the Arduino. I am not familiar with the driver board in your picture above, and I don't think it is supported by the Arduino stepper library, but uses a custom Arduino library. If you want to use that board, you will need to modify the firmata-express sketch to support it. This is a big job, but if you want to try and implement this, you can look at[ an article](https://www.instructables.com/id/Going-Beyond-StandardFirmata-Adding-New-Device-Sup/) I wrote several years back on how to add the Arduino stepper library to firmata as a guide.

**Comment by HotView** [comment]
@MrYsLab 

Hello, I communicated with you on github just now, but since I am studying in China, I can't access websites like Google and github on my network, so the network is blocked again.

At present, I need to use Python to control an Arduino so that it can control the stepper motor to take different steps according to different external signals. However, after the discussion just now, I found that the stepper function does not support the motor driver I want to use.

I would like to ask whether the pins in firmata-express can be controlled to generate PWM?If this is possible, I can use a pin to generate a PWM wave to control my motor driver.

**Comment by MrYsLab** [comment]
Yes, it supports PWM. Here is a [simple example](https://github.com/MrYsLab/pymata-express/blob/master/examples/analog_output.py).

**Comment by MrYsLab** [comment]
I am closing this issue. If you have any additional questions you can post them here and I will see them.

**Comment by panchalmanish2208** [comment]
how to connect or control 2 or 3 stepper motor  using pymata ? Pls give some example for the same

**Comment by MrYsLab** [comment]
@Manish2208 Hi again. None of my Firmata sketches support more than 1 stepper motor. If you are looking for a source about wiring up stepper motors, please check the following links:
https://learn.sparkfun.com/tutorials/easy-driver-hook-up-guide
https://learn.adafruit.com/adafruit-motor-selection-guide

Unless your project requires the precision of a stepper motor, you may wish to consider using either DC motors or Servo motors. Firmata can easily support a multiple of each type.
